apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  sausage-store.conf: |
    server {

      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://{{ .Values.backend.host }}:{{ .Values.backend.port }};
      }
    }
